import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Nav from '../components/nav'
import StatusProc from '../components/StatusProc'

export default function Home() {
  return (
    <div className={styles.home}>
      <Head>
        <title>Trámites y Citas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav/>

      <main className={styles.main}>
        <StatusProc/>

        </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
